export const btn = {
    backgroundColor: "rgba(51, 51, 51, 0.05)",
    borderRadius: 8,
    borderWidth: 0,
    color: "#333333",
    cursor: "pointer",
    display: "inline-block",
    fontFamily: '"Haas Grot Text R Web", "Helvetica Neue", Helvetica, Arial, sans-serif',
    fontSize: 14,
    fontWeight: 700,
    listStyle: "none",
    margin: 0,
    padding: "10px 12px",
    textAlign: "center",
    transition: "all 200ms",
    verticalAlign: "baseline",
    whiteSpace: "nowrap",
    userSelect: "none",
    touchAction: "manipulation",
}